# Generated on phpdocker.io
version: "2"

services:
    test_nginx:
      #image: nginx:alpine
      #https://github.com/nginxinc/docker-nginx/blob/master/mainline/stretch-perl/Dockerfile
      build:
         context: ./docker/nginx
         dockerfile: Dockerfile
      container_name: test_nginx
      working_dir: /var/www
      volumes:
          - ./projects:/var/www
          - ./docker/nginx/conf.d:/etc/nginx/conf.d/
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./docker_var/logs/nginx:/var/log/nginx
      ports:
       - "80:80"

    test_php-fpm:
      build:
         context: ./docker/php-fpm
         dockerfile: Dockerfile
      container_name: test_php-fpm
      working_dir: /var/www
      volumes:
        - ./projects:/var/www
        - ./docker/php-fpm/pool.d:/etc/php/7.2/fpm/pool.d
        - ./docker_var/logs/php-fpm/:/var/log/
      ports:
       - "9000:9000"
